param([switch]$Fast,[switch]$Clean,[switch]$Ci,[switch]$Diagnose)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Root=Split-Path -Parent $PSScriptRoot;Set-Location $Root
$App='Vacancy Parser Pro';$Version='4.9';$NumericVersion='4.9.0.0';$Entry='vacancy_parser.py';$PythonSeries='3.13'
$PyInstaller='6.22.3';$Hooks='2026.7'
$PythonInstallerUrl='https://www.python.org/ftp/python/3.13.15/python-3.13.15-amd64.exe';$PythonInstallerHash='edec09c4853aeae9ac36efb8c9f95b6b8e2fee65eee56d9767a8b7c69c574403'
$Venv=Join-Path $Root '.build-venv';$Py=Join-Path $Venv 'Scripts\python.exe';$Work=Join-Path $Root '.build';$Cache=Join-Path $Root '.build-cache';$Logs=Join-Path $Root 'build_logs';$Dist=Join-Path $Root 'dist';$Prev=Join-Path $Root 'dist_previous';$Stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$Log=Join-Path $Logs "build_$Stamp.log";$Summary=Join-Path $Logs 'last_build_summary.json';$Stage='bootstrap';$Transcript=$false;$BasePython=$null;$GitCommit='source-archive'
function Step($m){Write-Host "[$Stage] $m"}
function Remove-Safe($p){if(Test-Path -LiteralPath $p){Remove-Item -LiteralPath $p -Recurse -Force}}
function Run([string]$exe,[string[]]$args,[string]$label){Write-Host "[RUN] $label";& $exe @args;if($LASTEXITCODE -ne 0){throw "$label failed with exit code $LASTEXITCODE"}}
function Timed([string]$exe,[string[]]$args,[int]$sec,[string]$cwd){$p=Start-Process -FilePath $exe -ArgumentList $args -WorkingDirectory $cwd -PassThru;if(-not$p.WaitForExit($sec*1000)){try{$p.Kill()}catch{};throw "Timed out after $sec seconds: $exe"};if($p.ExitCode -ne 0){throw "Packaged process failed with exit code $($p.ExitCode)"}}
function Probe-Python($exe){try{$x=& $exe -c "import json,platform,sys;print(json.dumps({'exe':sys.executable,'series':f'{sys.version_info[0]}.{sys.version_info[1]}','version':platform.python_version(),'arch':platform.architecture()[0]}))" 2>$null;if($LASTEXITCODE -ne 0-or-not$x){return $null};$i=($x|Select-Object -Last 1)|ConvertFrom-Json;if($i.series-ne$PythonSeries-or$i.arch-ne'64bit'){return $null};[pscustomobject]@{exe=[string]$i.exe;version=[string]$i.version}}catch{$null}}
function Find-Python{if($env:pythonLocation){$p=Join-Path $env:pythonLocation 'python.exe';if(Test-Path $p){$r=Probe-Python $p;if($r){return$r}}};if(Get-Command py.exe -ErrorAction SilentlyContinue){try{$p=& py.exe -3.13 -c "import sys;print(sys.executable)" 2>$null;if($LASTEXITCODE-eq0-and$p){$r=Probe-Python ($p|Select-Object -Last 1);if($r){return$r}}}catch{}};foreach($p in @((Join-Path $env:LOCALAPPDATA 'Programs\Python\Python313\python.exe'),(Join-Path $env:ProgramFiles 'Python313\python.exe'))){if(Test-Path $p){$r=Probe-Python $p;if($r){return$r}}};$c=Get-Command python.exe -ErrorAction SilentlyContinue;if($c){$r=Probe-Python $c.Source;if($r){return$r}};$null}
function Download($uri,$dest){for($n=1;$n-le3;$n++){try{Write-Host "[DOWNLOAD] $uri ($n/3)";Invoke-WebRequest -UseBasicParsing -Uri $uri -OutFile $dest -TimeoutSec 180;return}catch{if($n-eq3){throw};Start-Sleep -Seconds(2*$n)}}}
function Ensure-Python{$r=Find-Python;if($r){return$r};if($Ci){throw 'Python 3.13 x64 is missing in CI.'};$w=Get-Command winget.exe -ErrorAction SilentlyContinue;if($w){try{& $w.Source install --id Python.Python.3.13 -e --scope user --silent --accept-source-agreements --accept-package-agreements;if($LASTEXITCODE-eq0){$r=Find-Python;if($r){return$r}}}catch{}};New-Item -ItemType Directory -Force -Path $Cache|Out-Null;$i=Join-Path $Cache 'python-3.13.15-amd64.exe';if(-not(Test-Path $i)){Download $PythonInstallerUrl $i};if((Get-FileHash $i -Algorithm SHA256).Hash.ToLowerInvariant()-ne$PythonInstallerHash){Remove-Item $i -Force -ErrorAction SilentlyContinue;throw 'Python installer SHA-256 mismatch.'};$p=Start-Process $i -ArgumentList @('/quiet','InstallAllUsers=0','PrependPath=0','Include_launcher=1','Include_pip=1','Include_test=0','SimpleInstall=1') -PassThru -Wait;if($p.ExitCode-ne0){throw "Python installer failed: $($p.ExitCode)"};$r=Find-Python;if(-not$r){throw 'Python installed but was not found.'};$r}
function Commit-Id{$g=Get-Command git.exe -ErrorAction SilentlyContinue;if(-not$g){return'source-archive'};try{$v=&$g.Source -C $Root rev-parse HEAD 2>$null;if($LASTEXITCODE-eq0-and$v){return($v|Select-Object -Last 1).Trim()}}catch{};'source-archive'}
function Summary($status,$err=$null,$artifact=$null){New-Item -ItemType Directory -Force -Path $Logs|Out-Null;[ordered]@{schema=1;app=$App;app_version=$Version;status=$status;stage=$Stage;error=$err;artifact=$artifact;generated_at_utc=[DateTime]::UtcNow.ToString('o');git_commit=$GitCommit;python=if($BasePython){$BasePython.version}else{$null};pyinstaller=$PyInstaller;fast=[bool]$Fast;clean=[bool]$Clean;ci=[bool]$Ci;diagnose=[bool]$Diagnose}|ConvertTo-Json -Depth 4|Set-Content $Summary -Encoding UTF8}
function Preflight{$script:Stage='preflight';Step 'Checking Windows x64, resources, write access and disk space...';if($env:OS-ne'Windows_NT'){throw'Windows only.'};if($env:PROCESSOR_ARCHITECTURE-ne'AMD64'){throw"x64 release build required; detected $env:PROCESSOR_ARCHITECTURE"};foreach($f in @($Entry,'vacancy_gui.py','job_scraper.py','problem_logging.py','requirements.txt','icon.ico')){if(-not(Test-Path(Join-Path $Root $f))){throw"Missing required file: $f"}};$probe=Join-Path $Root '.build_probe.tmp';try{'ok'|Set-Content $probe -Encoding ASCII}finally{Remove-Item $probe -Force -ErrorAction SilentlyContinue};$d=Get-PSDrive -Name(([IO.Path]::GetPathRoot($Root)).Substring(0,1));if($d.Free-lt3GB){throw'At least 3 GB free space is required.'};Write-Host "[INFO] Free space: $([Math]::Round($d.Free/1GB,2)) GB"}
function Toolchain{$script:Stage='toolchain';if($Clean){Remove-Safe $Venv;Remove-Safe $Cache;Remove-Safe $Work};$script:BasePython=Ensure-Python;Write-Host "[INFO] Python: $($BasePython.version) at $($BasePython.exe)";if($Diagnose){return};if(Test-Path $Py){if(-not(Probe-Python $Py)){Remove-Safe $Venv}};if(-not(Test-Path $Py)){Run $BasePython.exe @('-m','venv',$Venv) 'Create build venv'};$marker=Join-Path $Venv '.toolchain-id';$runtime=(Get-Content (Join-Path $Root 'requirements.txt') -Raw).Trim();$expected="$runtime`npyinstaller==$PyInstaller`npyinstaller-hooks-contrib==$Hooks";$current=if(Test-Path $marker){(Get-Content $marker -Raw).Trim()}else{''};if(-not$Fast-or$current-ne$expected){Run $Py @('-m','pip','install','--disable-pip-version-check','--no-input','--timeout','60','--retries','2','-r','requirements.txt') 'Install runtime dependencies';Run $Py @('-m','pip','install','--disable-pip-version-check','--no-input','--timeout','60','--retries','2',"pyinstaller==$PyInstaller","pyinstaller-hooks-contrib==$Hooks") 'Install build toolchain';$expected|Set-Content $marker -Encoding UTF8};Run $Py @('-m','pip','check') 'pip check'}
function Metadata{$script:Stage='metadata';$d=Join-Path $Work 'metadata';New-Item -ItemType Directory -Force -Path $d|Out-Null;$m=Join-Path $d 'app.manifest';$v=Join-Path $d 'version.txt';@"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"><assemblyIdentity version="$NumericVersion" processorArchitecture="amd64" name="Vacancy.Parser.Pro" type="win32"/><trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"><security><requestedPrivileges><requestedExecutionLevel level="asInvoker" uiAccess="false"/></requestedPrivileges></security></trustInfo><application xmlns="urn:schemas-microsoft-com:asm.v3"><windowsSettings><dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness><longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware></windowsSettings></application></assembly>
"@|Set-Content $m -Encoding UTF8;@"
VSVersionInfo(ffi=FixedFileInfo(filevers=(4,9,0,0),prodvers=(4,9,0,0),mask=0x3f,flags=0x0,OS=0x40004,fileType=0x1,subtype=0x0,date=(0,0)),kids=[StringFileInfo([StringTable('040904B0',[StringStruct('CompanyName','Dmitry Kolesnichenko'),StringStruct('FileDescription','Vacancy Parser Pro'),StringStruct('FileVersion','4.9.0.0'),StringStruct('OriginalFilename','Vacancy Parser Pro.exe'),StringStruct('ProductName','Vacancy Parser Pro'),StringStruct('ProductVersion','4.9')])]),VarFileInfo([VarStruct('Translation',[1033,1200])])])
"@|Set-Content $v -Encoding UTF8;[pscustomobject]@{manifest=$m;version=$v}}
function Source-Test{$script:Stage='source-verification';Run $Py @('-m','compileall','-q','vacancy_parser.py','vacancy_gui.py','job_scraper.py','problem_logging.py','tests') 'Compile sources';Run $Py @('-m','unittest','discover','-s','tests','-v') 'Unit tests';Run $Py @($Entry,'--self-test') 'Source self-test'}
function Package($meta){$script:Stage='pyinstaller';$s=Join-Path $Work 'stage-dist';$w=Join-Path $Work 'pyinstaller-work';$sp=Join-Path $Work 'spec';Remove-Safe $s;if(-not$Fast){Remove-Safe $w};Remove-Safe $sp;New-Item -ItemType Directory -Force -Path $s,$w,$sp|Out-Null;$a=@('-m','PyInstaller','--noconfirm','--onefile','--windowed','--noupx','--name',$App,'--icon','icon.ico','--distpath',$s,'--workpath',$w,'--specpath',$sp,'--manifest',$meta.manifest,'--version-file',$meta.version);if(-not$Fast){$a+='--clean'};$a+=$Entry;Run $Py $a 'PyInstaller package';$e=Join-Path $s "$App.exe";if(-not(Test-Path $e)){throw'Expected EXE missing.'};if((Get-Item $e).Length-lt15MB){throw'EXE is unexpectedly small; refusing to publish likely incomplete build.'};$e}
function Verify($exe){$script:Stage='packaged-self-test';$cwd=Split-Path $exe -Parent;Copy-Item 'icon.ico' (Join-Path $cwd 'icon.ico') -Force;Timed $exe @('--self-test') 90 $cwd;$script:Stage='portable-folder-test';$t=Join-Path $env:TEMP ('Проверка Vacancy Parser '+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force -Path $t|Out-Null;try{Copy-Item $exe (Join-Path $t "$App.exe");Copy-Item 'icon.ico' (Join-Path $t 'icon.ico');Timed (Join-Path $t "$App.exe") @('--self-test') 90 $t}finally{Remove-Safe $t}}
function Publish($exe){$script:Stage='distribution';$p=Join-Path $Work 'package';$f=Join-Path $Work 'final-dist';Remove-Safe $p;Remove-Safe $f;New-Item -ItemType Directory -Force -Path $p,$f|Out-Null;$pe=Join-Path $p "$App.exe";Copy-Item $exe $pe;Copy-Item 'icon.ico' (Join-Path $p 'icon.ico');$eh=(Get-FileHash $pe -Algorithm SHA256).Hash.ToLowerInvariant();$script:GitCommit=Commit-Id;[ordered]@{schema=1;app=$App;app_version=$Version;artifact_type='onefile-portable-x64';built_at_utc=[DateTime]::UtcNow.ToString('o');git_commit=$GitCommit;python=$BasePython.version;pyinstaller=$PyInstaller;architecture='x64';exe="$App.exe";exe_sha256=$eh;resources=@('icon.ico');verification=@('compile','unit-tests','source-self-test','packaged-self-test','portable-folder-test','zip-extract-self-test')}|ConvertTo-Json -Depth 5|Set-Content (Join-Path $p 'build_info.json') -Encoding UTF8;$zn='Vacancy-Parser-Pro-portable-x64.zip';$z=Join-Path $Work $zn;Remove-Item $z -Force -ErrorAction SilentlyContinue;Compress-Archive -Path (Join-Path $p '*') -DestinationPath $z -CompressionLevel Optimal;$script:Stage='zip-verification';$t=Join-Path $env:TEMP ('Проверка ZIP Vacancy Parser '+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force -Path $t|Out-Null;try{Expand-Archive $z $t -Force;$ze=Join-Path $t "$App.exe";if((Get-FileHash $ze -Algorithm SHA256).Hash.ToLowerInvariant()-ne$eh){throw'ZIP EXE hash mismatch.'};if(-not(Test-Path(Join-Path $t 'icon.ico'))){throw'ZIP icon.ico missing.'};Timed $ze @('--self-test') 90 $t}finally{Remove-Safe $t};$zh=(Get-FileHash $z -Algorithm SHA256).Hash.ToLowerInvariant();Copy-Item $pe (Join-Path $f "$App.exe");Copy-Item 'icon.ico' (Join-Path $f 'icon.ico');Copy-Item (Join-Path $p 'build_info.json') (Join-Path $f 'build_info.json');Copy-Item $z (Join-Path $f $zn);@("$eh *$App.exe","$zh *$zn")|Set-Content (Join-Path $f 'SHA256SUMS.txt') -Encoding ASCII;$script:Stage='atomic-publish';Remove-Safe $Prev;if(Test-Path $Dist){Move-Item $Dist $Prev};try{Move-Item $f $Dist}catch{if((-not(Test-Path $Dist))-and(Test-Path $Prev)){Move-Item $Prev $Dist};throw};Join-Path $Dist "$App.exe"}
$rc=0;try{New-Item -ItemType Directory -Force -Path $Logs|Out-Null;Get-ChildItem $Logs -Filter 'build_*.log' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -Skip 20|Remove-Item -Force -ErrorAction SilentlyContinue;try{Start-Transcript $Log -Force|Out-Null;$Transcript=$true}catch{};$GitCommit=Commit-Id;Preflight;Toolchain;if($Diagnose){$Stage='diagnose-complete';Summary 'diagnose-ok';Write-Host '[OK] Diagnostic preflight completed.'}else{New-Item -ItemType Directory -Force -Path $Work|Out-Null;$m=Metadata;Source-Test;$e=Package $m;Verify $e;$a=Publish $e;$Stage='complete';Summary 'success' $null $a;Write-Host '';Write-Host '[OK] READY BUILD CREATED AND VERIFIED';Write-Host "EXE: $a";Write-Host "ZIP: $(Join-Path $Dist 'Vacancy-Parser-Pro-portable-x64.zip')"}}catch{$rc=1;$msg=$_.Exception.Message;Write-Host "[ERROR] Build failed at '$Stage': $msg" -ForegroundColor Red;try{Summary 'failed' $msg}catch{};Write-Host '[INFO] Existing dist was not replaced by an unverified candidate.'}finally{if($Transcript){try{Stop-Transcript|Out-Null}catch{}}};exit $rc
